import{CONFIG}from'./config.js';import{saveRemote}from'./api.js';
const rupiah=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const catalog=[{code:'CASH_DEPOSIT',title:'Setoran Kas',desc:'Hitung semua pecahan uang',icon:'▦',tone:'lime'},{code:'SELLING_PRICE',title:'Harga Jual',desc:'HPP, margin, dan laba',icon:'%',tone:'blue'},{code:'DISCOUNT',title:'Diskon',desc:'Harga akhir dan penghematan',icon:'−',tone:'violet'},{code:'MARKETPLACE_FEE',title:'Biaya Marketplace',desc:'Fee dan penerimaan bersih',icon:'↗',tone:'orange'}];let active='CASH_DEPOSIT',currentResult={};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function field(id,label,value,suffix=''){return`<label class="number-field"><span>${label}</span><div><input id="${id}" type="number" min="0" inputmode="decimal" value="${value}">${suffix?`<b>${suffix}</b>`:''}</div></label>`}
function renderCatalog(items=catalog){$('#calculatorGrid').innerHTML=items.map(x=>`<button class="calculator-card ${x.code===active?'active':''}" data-code="${x.code}"><i class="tone-${x.tone}">${x.icon}</i><span><b>${x.title}</b><small>${x.desc}</small></span><em>→</em></button>`).join('');$('#resultCount').textContent=`${items.length} kalkulator ditemukan`;$$('.calculator-card').forEach(b=>b.onclick=()=>select(b.dataset.code,true))}
function renderTabs(){$('#calculatorTabs').innerHTML=catalog.map(x=>`<button class="${x.code===active?'active':''}" data-code="${x.code}">${x.title}</button>`).join('');$$('#calculatorTabs button').forEach(b=>b.onclick=()=>select(b.dataset.code))}
function select(code,scroll=false){active=code;renderCatalog(filterCatalog($('#calculatorSearch').value));renderTabs();renderCalculator();if(scroll)$('#workspace').scrollIntoView({behavior:'smooth'})}
function filterCatalog(term){term=term.trim().toLowerCase();return term?catalog.filter(x=>`${x.title} ${x.desc} ${x.code}`.toLowerCase().includes(term)):catalog}
function renderCalculator(){if(active==='CASH_DEPOSIT')return renderCash();const data=active==='SELLING_PRICE'?{title:'Kalkulator Harga Jual',a:['amount','HPP / modal produk',100000],b:['rate','Target margin',35],c:['cost','Biaya tambahan',15000]}:active==='DISCOUNT'?{title:'Kalkulator Diskon',a:['amount','Harga awal',250000],b:['rate','Besaran diskon',20]}:{title:'Biaya Marketplace',a:['amount','Harga jual',100000],b:['rate','Biaya layanan',8],c:['cost','Biaya tetap',1250]};$('#calculatorPanel').innerHTML=`<header class="calculator-header"><div><span class="eyebrow">CALPRO SMART ENGINE</span><h2>${data.title}</h2></div></header><div class="field-grid">${field(...data.a)}${field(...data.b,'%')}${data.c?field(...data.c):''}</div><section class="result-panel" aria-live="polite"><span id="resultLabel"></span><strong id="resultValue"></strong><small>Dihitung otomatis saat input berubah</small></section><div class="result-details"><span id="detailLabel"></span><span>Persentase<b id="rateValue"></b></span></div>`;$$('#calculatorPanel input').forEach(i=>i.oninput=calculateStandard);calculateStandard()}
function calculateStandard(){const amount=+$('#amount').value||0,rate=+$('#rate').value||0,cost=$('#cost')?+$('#cost').value||0:0;let result=0,detail=0,label='',detailLabel='';if(active==='SELLING_PRICE'){result=rate>=100?0:Math.ceil((amount+cost)/(1-rate/100)/1000)*1000;detail=result-amount-cost;label='Harga jual rekomendasi';detailLabel='Laba per produk'}else if(active==='DISCOUNT'){detail=amount*rate/100;result=amount-detail;label='Harga setelah diskon';detailLabel='Pelanggan hemat'}else{detail=amount*rate/100+cost;result=amount-detail;label='Penerimaan bersih';detailLabel='Total biaya'}$('#resultLabel').textContent=label;$('#resultValue').textContent=rupiah.format(result);$('#detailLabel').innerHTML=`${detailLabel}<b>${rupiah.format(detail)}</b>`;$('#rateValue').textContent=`${rate}%`;currentResult={input:{amount,rate,cost},result:{value:result,detail},title:label}}
function renderCash(){const pieces=[100000,50000,20000,10000,5000,2000,1000,500];$('#calculatorPanel').innerHTML=`<header class="calculator-header"><div><span class="eyebrow">KAS & SETORAN</span><h2>Kalkulator Setoran</h2></div><button class="button button-secondary" id="resetCash">Reset</button></header><div class="cash-grid">${pieces.map((p,i)=>`<div class="cash-row"><span><small>PECAHAN</small><b>${rupiah.format(p)}</b></span><div class="stepper"><button data-step="-1">−</button><input data-piece="${p}" inputmode="numeric" value="${i===0?10:i===1?4:i===2?5:''}"><button data-step="1">+</button></div><strong>Rp0</strong></div>`).join('')}</div><div class="target-field">${field('cashTarget','Setoran menurut catatan',1300000)}</div><section class="cash-summary"><span>Total aktual<b id="cashTotal"></b></span><span>Selisih<b id="cashDifference"></b></span><em id="cashState"></em></section>`;$$('.stepper button').forEach(b=>b.onclick=()=>{const input=b.parentElement.querySelector('input');input.value=Math.max(0,(+input.value||0)+(+b.dataset.step));calculateCash()});$$('.stepper input, #cashTarget').forEach(i=>i.oninput=calculateCash);$('#resetCash').onclick=()=>{$$('.stepper input').forEach(i=>i.value='');calculateCash()};calculateCash()}
function calculateCash(){let total=0;$$('.stepper input').forEach(i=>{const subtotal=(+i.dataset.piece)*(+i.value||0);total+=subtotal;i.closest('.cash-row').querySelector('strong').textContent=rupiah.format(subtotal)});const target=+$('#cashTarget').value||0,difference=total-target;$('#cashTotal').textContent=rupiah.format(total);$('#cashDifference').textContent=rupiah.format(difference);$('#cashDifference').className=difference===0?'ok':'warn';$('#cashState').textContent=difference===0?'Sesuai':difference<0?'Kurang':'Lebih';$('#cashState').className=difference===0?'good':'bad';currentResult={input:{target,denominations:$$('.stepper input').map(i=>({value:+i.dataset.piece,quantity:+i.value||0}))},result:{total,difference},title:'Setoran Kas'}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function buildRecord(){return{calculationId:`CAL-${Date.now()}`,requestId:crypto.randomUUID(),tenantId:CONFIG.tenantId,userId:CONFIG.userId,appId:CONFIG.appId,calculatorCode:active,...currentResult,status:'ACTIVE',syncStatus:'PENDING',createdAt:new Date().toISOString()}}
function saveLocal(message='Draft tersimpan di perangkat'){const records=JSON.parse(localStorage.getItem(CONFIG.storageKey)||'[]'),record=buildRecord();records.unshift(record);localStorage.setItem(CONFIG.storageKey,JSON.stringify(records.slice(0,100)));toast(message);return record}
$('#calculatorSearch').oninput=e=>renderCatalog(filterCatalog(e.target.value));$('#saveDraft').onclick=()=>saveLocal();$('#saveCalculation').onclick=async()=>{const record=saveLocal('Disimpan lokal, sedang sinkronisasi');try{const response=await saveRemote(record);toast(response.pending?'Menunggu URL Apps Script':'Perhitungan tersinkron')}catch{toast('Offline: data aman di perangkat')}};$$('[data-scroll]').forEach(b=>b.onclick=()=>$('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth'}));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));renderCatalog();renderTabs();renderCalculator();
